### ISSUE TITLE
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array. 

### ISSUE THREAD

**Issue by BopItFreak** [zefie/zef-xiso-convert#3]
![image](https://user-images.githubusercontent.com/41522720/105925061-7fce4d00-600d-11eb-96a3-ad5cb1328735.png)

**Comment by zefie** [comment]
I feel like something changed in .NET since I built this application, I used it the other day and realized I had to add a dummy argument. I forgot which side of the actual filename it goes on, so try the following:

`zef-xiso-convert.exe "../../Roms/ISO/etc..." .`
or
`zef-xiso-convert.exe . "../../Roms/ISO/etc..." `

**Comment by perguto** [comment]
```
zef-xiso-convert.exe "../../Roms/ISO/etc..." .
```
works
